version: "2"
run:
  timeout: 2m
  build-tags:
    - codeanalysis
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - wsl
    - err113
    - wsl_v5
    - depguard
    - exhaustruct
    - varnamelen
    - noinlineerr
    - godox
    - wrapcheck
    - modernize
    - perfsprint
    - ireturn
    - mnd
  settings:
    lll:
      line-length: 140
      tab-width: 2
    cyclop:
      max-complexity: 20
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
    goimports:
      local-prefixes:
        - github.com/xgamtx/go-mockery-descriptor
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
