constructor-name: "newMock{{ . }}"
package-name: "{{ . }}"
output: "{{ . }}.gen_test.go"
interfaces:
  - name: Some
    field-overwriter-param:
      - Slice.rows=elementsMatch
      - SetX.x=oneOf
      - Anything.v=any
    rename-returns:
      GetX.r0: X
      Multi.r0: X
      Multi.r1: Y