// Code generated by go-mockery-descriptor v1.0.0. DO NOT EDIT.

package app

import (
	"io"
	"testing"

	"github.com/stretchr/testify/mock"
)

type ownCall struct {
	X           int
	ReceivedR0  string
	ReceivedErr error
}

type pingCall struct {
	ReceivedErr error
}

type readFromCall struct {
	R           io.Reader
	ReceivedN   int64
	ReceivedErr error
}

type embeddedCalls struct {
	Own      []ownCall
	Ping     []pingCall
	ReadFrom []readFromCall
}

func makeEmbeddedMock(t *testing.T, calls *embeddedCalls) Embedded {
	t.Helper()
	m := newMockEmbedded(t)
	anyCtx := mock.Anything
	for _, call := range calls.Own {
		m.EXPECT().Own(call.X).Return(call.ReceivedR0, call.ReceivedErr).Once()
	}
	for _, call := range calls.Ping {
		m.EXPECT().Ping(anyCtx).Return(call.ReceivedErr).Once()
	}
	for _, call := range calls.ReadFrom {
		m.EXPECT().ReadFrom(call.R).Return(call.ReceivedN, call.ReceivedErr).Once()
	}

	return m
}
