// Code generated by go-mockery-descriptor v1.0.0. DO NOT EDIT.

package app

import (
	"testing"

	"github.com/stretchr/testify/mock"
	"github.com/xgamtx/go-mockery-descriptor/pkg/assessor"
)

type filterCall struct {
	Rows []string
	Mode []int

	ReceivedErr error
}

func makeFilterMock(t *testing.T, calls []filterCall) Filter {
	t.Helper()
	m := newMockFilter(t)
	for _, call := range calls {
		m.EXPECT().Execute(assessor.ElementsMatch(call.Rows), assessor.OneOf(call.Mode), mock.Anything).Return(call.ReceivedErr).Once()
	}

	return m.Execute
}
