// Code generated by go-mockery-descriptor v1.0.0. DO NOT EDIT.

package app

import (
	"testing"

	"github.com/stretchr/testify/mock"
)

type handlerCall struct {
	Id             string
	ReceivedResult string
	ReceivedErr    error
}

func makeHandlerMock(t *testing.T, calls []handlerCall) Handler {
	t.Helper()
	m := newMockHandler(t)
	anyCtx := mock.Anything
	for _, call := range calls {
		m.EXPECT().Execute(anyCtx, call.Id).Return(call.ReceivedResult, call.ReceivedErr).Once()
	}

	return m.Execute
}
