// Code generated by mockery v2.53.5. DO NOT EDIT.

package app

import mock "github.com/stretchr/testify/mock"

// mockFilter is an autogenerated mock type for the Filter type
type mockFilter struct {
	mock.Mock
}

type mockFilter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFilter) EXPECT() *mockFilter_Expecter {
	return &mockFilter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: rows, mode, ignored
func (_m *mockFilter) Execute(rows []string, mode int, ignored bool) error {
	ret := _m.Called(rows, mode, ignored)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, int, bool) error); ok {
		r0 = rf(rows, mode, ignored)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockFilter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockFilter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - rows []string
//   - mode int
//   - ignored bool
func (_e *mockFilter_Expecter) Execute(rows interface{}, mode interface{}, ignored interface{}) *mockFilter_Execute_Call {
	return &mockFilter_Execute_Call{Call: _e.mock.On("Execute", rows, mode, ignored)}
}

func (_c *mockFilter_Execute_Call) Run(run func(rows []string, mode int, ignored bool)) *mockFilter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string), args[1].(int), args[2].(bool))
	})
	return _c
}

func (_c *mockFilter_Execute_Call) Return(_a0 error) *mockFilter_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockFilter_Execute_Call) RunAndReturn(run func([]string, int, bool) error) *mockFilter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockFilter creates a new instance of mockFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFilter {
	mock := &mockFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
