// Code generated by mockery v2.53.5. DO NOT EDIT.

package app

import mock "github.com/stretchr/testify/mock"

// mockTicker is an autogenerated mock type for the Ticker type
type mockTicker struct {
	mock.Mock
}

type mockTicker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTicker) EXPECT() *mockTicker_Expecter {
	return &mockTicker_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *mockTicker) Execute() {
	_m.Called()
}

// mockTicker_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockTicker_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *mockTicker_Expecter) Execute() *mockTicker_Execute_Call {
	return &mockTicker_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *mockTicker_Execute_Call) Run(run func()) *mockTicker_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTicker_Execute_Call) Return() *mockTicker_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockTicker_Execute_Call) RunAndReturn(run func()) *mockTicker_Execute_Call {
	_c.Run(run)
	return _c
}

// newMockTicker creates a new instance of mockTicker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTicker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTicker {
	mock := &mockTicker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
