// Code generated by mockery v2.53.5. DO NOT EDIT.

package app

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockEmbedded is an autogenerated mock type for the Embedded type
type mockEmbedded struct {
	mock.Mock
}

type mockEmbedded_Expecter struct {
	mock *mock.Mock
}

func (_m *mockEmbedded) EXPECT() *mockEmbedded_Expecter {
	return &mockEmbedded_Expecter{mock: &_m.Mock}
}

// Own provides a mock function with given fields: x
func (_m *mockEmbedded) Own(x int) (string, error) {
	ret := _m.Called(x)

	if len(ret) == 0 {
		panic("no return value specified for Own")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(x)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(x)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(x)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockEmbedded_Own_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Own'
type mockEmbedded_Own_Call struct {
	*mock.Call
}

// Own is a helper method to define mock.On call
//   - x int
func (_e *mockEmbedded_Expecter) Own(x interface{}) *mockEmbedded_Own_Call {
	return &mockEmbedded_Own_Call{Call: _e.mock.On("Own", x)}
}

func (_c *mockEmbedded_Own_Call) Run(run func(x int)) *mockEmbedded_Own_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *mockEmbedded_Own_Call) Return(_a0 string, _a1 error) *mockEmbedded_Own_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockEmbedded_Own_Call) RunAndReturn(run func(int) (string, error)) *mockEmbedded_Own_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *mockEmbedded) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockEmbedded_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type mockEmbedded_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockEmbedded_Expecter) Ping(ctx interface{}) *mockEmbedded_Ping_Call {
	return &mockEmbedded_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *mockEmbedded_Ping_Call) Run(run func(ctx context.Context)) *mockEmbedded_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockEmbedded_Ping_Call) Return(_a0 error) *mockEmbedded_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockEmbedded_Ping_Call) RunAndReturn(run func(context.Context) error) *mockEmbedded_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFrom provides a mock function with given fields: r
func (_m *mockEmbedded) ReadFrom(r io.Reader) (int64, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ReadFrom")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Reader) (int64, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(io.Reader) int64); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockEmbedded_ReadFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFrom'
type mockEmbedded_ReadFrom_Call struct {
	*mock.Call
}

// ReadFrom is a helper method to define mock.On call
//   - r io.Reader
func (_e *mockEmbedded_Expecter) ReadFrom(r interface{}) *mockEmbedded_ReadFrom_Call {
	return &mockEmbedded_ReadFrom_Call{Call: _e.mock.On("ReadFrom", r)}
}

func (_c *mockEmbedded_ReadFrom_Call) Run(run func(r io.Reader)) *mockEmbedded_ReadFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader))
	})
	return _c
}

func (_c *mockEmbedded_ReadFrom_Call) Return(n int64, err error) *mockEmbedded_ReadFrom_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockEmbedded_ReadFrom_Call) RunAndReturn(run func(io.Reader) (int64, error)) *mockEmbedded_ReadFrom_Call {
	_c.Call.Return(run)
	return _c
}

// newMockEmbedded creates a new instance of mockEmbedded. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEmbedded(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEmbedded {
	mock := &mockEmbedded{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
