// Code generated by go-mockery-descriptor v1.0.0. DO NOT EDIT.

package app

import (
	"testing"
)

type tickerCall struct{}

func makeTickerMock(t *testing.T, calls []tickerCall) Ticker {
	t.Helper()
	m := newMockTicker(t)
	for range calls {
		m.EXPECT().Execute().Return().Once()
	}

	return m.Execute
}
