// Code generated by mockery v2.53.5. DO NOT EDIT.

package app

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockSome is an autogenerated mock type for the Some type
type MockSome struct {
	mock.Mock
}

type MockSome_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSome) EXPECT() *MockSome_Expecter {
	return &MockSome_Expecter{mock: &_m.Mock}
}

// GetX provides a mock function with given fields: ctx
func (_m *MockSome) GetX(ctx context.Context) string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetX")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSome_GetX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetX'
type MockSome_GetX_Call struct {
	*mock.Call
}

// GetX is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSome_Expecter) GetX(ctx interface{}) *MockSome_GetX_Call {
	return &MockSome_GetX_Call{Call: _e.mock.On("GetX", ctx)}
}

func (_c *MockSome_GetX_Call) Run(run func(ctx context.Context)) *MockSome_GetX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSome_GetX_Call) Return(_a0 string) *MockSome_GetX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSome_GetX_Call) RunAndReturn(run func(context.Context) string) *MockSome_GetX_Call {
	_c.Call.Return(run)
	return _c
}

// M provides a mock function with given fields: m
func (_m *MockSome) M(m map[string]pgx.Tx) map[string]pgx.Tx {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for M")
	}

	var r0 map[string]pgx.Tx
	if rf, ok := ret.Get(0).(func(map[string]pgx.Tx) map[string]pgx.Tx); ok {
		r0 = rf(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]pgx.Tx)
		}
	}

	return r0
}

// MockSome_M_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'M'
type MockSome_M_Call struct {
	*mock.Call
}

// M is a helper method to define mock.On call
//   - m map[string]pgx.Tx
func (_e *MockSome_Expecter) M(m interface{}) *MockSome_M_Call {
	return &MockSome_M_Call{Call: _e.mock.On("M", m)}
}

func (_c *MockSome_M_Call) Run(run func(m map[string]pgx.Tx)) *MockSome_M_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]pgx.Tx))
	})
	return _c
}

func (_c *MockSome_M_Call) Return(_a0 map[string]pgx.Tx) *MockSome_M_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSome_M_Call) RunAndReturn(run func(map[string]pgx.Tx) map[string]pgx.Tx) *MockSome_M_Call {
	_c.Call.Return(run)
	return _c
}

// Nothing provides a mock function with no fields
func (_m *MockSome) Nothing() {
	_m.Called()
}

// MockSome_Nothing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nothing'
type MockSome_Nothing_Call struct {
	*mock.Call
}

// Nothing is a helper method to define mock.On call
func (_e *MockSome_Expecter) Nothing() *MockSome_Nothing_Call {
	return &MockSome_Nothing_Call{Call: _e.mock.On("Nothing")}
}

func (_c *MockSome_Nothing_Call) Run(run func()) *MockSome_Nothing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSome_Nothing_Call) Return() *MockSome_Nothing_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSome_Nothing_Call) RunAndReturn(run func()) *MockSome_Nothing_Call {
	_c.Run(run)
	return _c
}

// SetX provides a mock function with given fields: tx, x
func (_m *MockSome) SetX(tx pgx.Tx, x string) error {
	ret := _m.Called(tx, x)

	if len(ret) == 0 {
		panic("no return value specified for SetX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pgx.Tx, string) error); ok {
		r0 = rf(tx, x)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSome_SetX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetX'
type MockSome_SetX_Call struct {
	*mock.Call
}

// SetX is a helper method to define mock.On call
//   - tx pgx.Tx
//   - x string
func (_e *MockSome_Expecter) SetX(tx interface{}, x interface{}) *MockSome_SetX_Call {
	return &MockSome_SetX_Call{Call: _e.mock.On("SetX", tx, x)}
}

func (_c *MockSome_SetX_Call) Run(run func(tx pgx.Tx, x string)) *MockSome_SetX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pgx.Tx), args[1].(string))
	})
	return _c
}

func (_c *MockSome_SetX_Call) Return(_a0 error) *MockSome_SetX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSome_SetX_Call) RunAndReturn(run func(pgx.Tx, string) error) *MockSome_SetX_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSome creates a new instance of MockSome. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSome(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSome {
	mock := &MockSome{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
