// Code generated by mockery v2.53.5. DO NOT EDIT.

package app

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// mockSome is an autogenerated mock type for the Some type
type mockSome struct {
	mock.Mock
}

type mockSome_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSome) EXPECT() *mockSome_Expecter {
	return &mockSome_Expecter{mock: &_m.Mock}
}

// Anything provides a mock function with given fields: v
func (_m *mockSome) Anything(v int) {
	_m.Called(v)
}

// mockSome_Anything_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Anything'
type mockSome_Anything_Call struct {
	*mock.Call
}

// Anything is a helper method to define mock.On call
//   - v int
func (_e *mockSome_Expecter) Anything(v interface{}) *mockSome_Anything_Call {
	return &mockSome_Anything_Call{Call: _e.mock.On("Anything", v)}
}

func (_c *mockSome_Anything_Call) Run(run func(v int)) *mockSome_Anything_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *mockSome_Anything_Call) Return() *mockSome_Anything_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockSome_Anything_Call) RunAndReturn(run func(int)) *mockSome_Anything_Call {
	_c.Run(run)
	return _c
}

// GetX provides a mock function with given fields: ctx
func (_m *mockSome) GetX(ctx context.Context) string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetX")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// mockSome_GetX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetX'
type mockSome_GetX_Call struct {
	*mock.Call
}

// GetX is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSome_Expecter) GetX(ctx interface{}) *mockSome_GetX_Call {
	return &mockSome_GetX_Call{Call: _e.mock.On("GetX", ctx)}
}

func (_c *mockSome_GetX_Call) Run(run func(ctx context.Context)) *mockSome_GetX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockSome_GetX_Call) Return(_a0 string) *mockSome_GetX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSome_GetX_Call) RunAndReturn(run func(context.Context) string) *mockSome_GetX_Call {
	_c.Call.Return(run)
	return _c
}

// M provides a mock function with given fields: m
func (_m *mockSome) M(m map[string]pgx.Tx) map[string]pgx.Tx {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for M")
	}

	var r0 map[string]pgx.Tx
	if rf, ok := ret.Get(0).(func(map[string]pgx.Tx) map[string]pgx.Tx); ok {
		r0 = rf(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]pgx.Tx)
		}
	}

	return r0
}

// mockSome_M_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'M'
type mockSome_M_Call struct {
	*mock.Call
}

// M is a helper method to define mock.On call
//   - m map[string]pgx.Tx
func (_e *mockSome_Expecter) M(m interface{}) *mockSome_M_Call {
	return &mockSome_M_Call{Call: _e.mock.On("M", m)}
}

func (_c *mockSome_M_Call) Run(run func(m map[string]pgx.Tx)) *mockSome_M_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]pgx.Tx))
	})
	return _c
}

func (_c *mockSome_M_Call) Return(_a0 map[string]pgx.Tx) *mockSome_M_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSome_M_Call) RunAndReturn(run func(map[string]pgx.Tx) map[string]pgx.Tx) *mockSome_M_Call {
	_c.Call.Return(run)
	return _c
}

// Nothing provides a mock function with no fields
func (_m *mockSome) Nothing() {
	_m.Called()
}

// mockSome_Nothing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nothing'
type mockSome_Nothing_Call struct {
	*mock.Call
}

// Nothing is a helper method to define mock.On call
func (_e *mockSome_Expecter) Nothing() *mockSome_Nothing_Call {
	return &mockSome_Nothing_Call{Call: _e.mock.On("Nothing")}
}

func (_c *mockSome_Nothing_Call) Run(run func()) *mockSome_Nothing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockSome_Nothing_Call) Return() *mockSome_Nothing_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockSome_Nothing_Call) RunAndReturn(run func()) *mockSome_Nothing_Call {
	_c.Run(run)
	return _c
}

// SetX provides a mock function with given fields: tx, x
func (_m *mockSome) SetX(tx pgx.Tx, x string) error {
	ret := _m.Called(tx, x)

	if len(ret) == 0 {
		panic("no return value specified for SetX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pgx.Tx, string) error); ok {
		r0 = rf(tx, x)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSome_SetX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetX'
type mockSome_SetX_Call struct {
	*mock.Call
}

// SetX is a helper method to define mock.On call
//   - tx pgx.Tx
//   - x string
func (_e *mockSome_Expecter) SetX(tx interface{}, x interface{}) *mockSome_SetX_Call {
	return &mockSome_SetX_Call{Call: _e.mock.On("SetX", tx, x)}
}

func (_c *mockSome_SetX_Call) Run(run func(tx pgx.Tx, x string)) *mockSome_SetX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pgx.Tx), args[1].(string))
	})
	return _c
}

func (_c *mockSome_SetX_Call) Return(_a0 error) *mockSome_SetX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSome_SetX_Call) RunAndReturn(run func(pgx.Tx, string) error) *mockSome_SetX_Call {
	_c.Call.Return(run)
	return _c
}

// Slice provides a mock function with given fields: rows
func (_m *mockSome) Slice(rows []string) error {
	ret := _m.Called(rows)

	if len(ret) == 0 {
		panic("no return value specified for Slice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(rows)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSome_Slice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Slice'
type mockSome_Slice_Call struct {
	*mock.Call
}

// Slice is a helper method to define mock.On call
//   - rows []string
func (_e *mockSome_Expecter) Slice(rows interface{}) *mockSome_Slice_Call {
	return &mockSome_Slice_Call{Call: _e.mock.On("Slice", rows)}
}

func (_c *mockSome_Slice_Call) Run(run func(rows []string)) *mockSome_Slice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *mockSome_Slice_Call) Return(_a0 error) *mockSome_Slice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSome_Slice_Call) RunAndReturn(run func([]string) error) *mockSome_Slice_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSome creates a new instance of mockSome. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSome(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSome {
	mock := &mockSome{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
