// Code generated by mock-galls-generator v1.0.0. DO NOT EDIT.

package app

import (
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/stretchr/testify/mock"

	"github.com/xgamtx/go-mockery-descriptor/pkg/assessor"
)

var (
	anyCtx = mock.Anything
	anyTx  = mock.Anything
)

type getXCall struct {
	ReceivedR0 string
}

type setXCall struct {
	X []string

	ReceivedR0 error
}

type nothingCall struct{}

type mCall struct {
	M map[string]pgx.Tx

	ReceivedR0 map[string]pgx.Tx
}

type sliceCall struct {
	Rows []string

	ReceivedR0 error
}

type someCalls struct {
	GetX    []getXCall
	SetX    []setXCall
	Nothing []nothingCall
	M       []mCall
	Slice   []sliceCall
}

func makeSomeMock(t *testing.T, calls *someCalls) Some {
	t.Helper()
	m := NewMockSome(t)
	for _, call := range calls.GetX {
		m.EXPECT().GetX(anyCtx).Return(call.ReceivedR0).Once()
	}
	for _, call := range calls.SetX {
		m.EXPECT().SetX(anyTx, assessor.OneOf(call.X)).Return(call.ReceivedR0).Once()
	}
	for range calls.Nothing {
		m.EXPECT().Nothing().Return().Once()
	}
	for _, call := range calls.M {
		m.EXPECT().M(call.M).Return(call.ReceivedR0).Once()
	}
	for _, call := range calls.Slice {
		m.EXPECT().Slice(assessor.ElementsMatch(call.Rows)).Return(call.ReceivedR0).Once()
	}
	return m
}
