// Code generated by go-mockery-descriptor v1.0.0. DO NOT EDIT.

package app

import (
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/stretchr/testify/mock"

	"github.com/xgamtx/go-mockery-descriptor/pkg/assessor"
)

type getXCall struct {
	ReceivedR0 string
}

type setXCall struct {
	X []string

	ReceivedErr error
}

type nothingCall struct{}

type mCall struct {
	M map[string]pgx.Tx

	ReceivedR0 map[string]pgx.Tx
}

type sliceCall struct {
	Rows []string

	ReceivedErr error
}

type anythingCall struct{}

type someCalls struct {
	GetX     []getXCall
	SetX     []setXCall
	Nothing  []nothingCall
	M        []mCall
	Slice    []sliceCall
	Anything []anythingCall
}

func makeSomeMock(t *testing.T, calls *someCalls) Some {
	t.Helper()
	m := newMockSome(t)
	anyCtx := mock.Anything
	anyTx := mock.Anything
	for _, call := range calls.GetX {
		m.EXPECT().GetX(anyCtx).Return(call.ReceivedR0).Once()
	}
	for _, call := range calls.SetX {
		m.EXPECT().SetX(anyTx, assessor.OneOf(call.X)).Return(call.ReceivedErr).Once()
	}
	for range calls.Nothing {
		m.EXPECT().Nothing().Return().Once()
	}
	for _, call := range calls.M {
		m.EXPECT().M(call.M).Return(call.ReceivedR0).Once()
	}
	for _, call := range calls.Slice {
		m.EXPECT().Slice(assessor.ElementsMatch(call.Rows)).Return(call.ReceivedErr).Once()
	}
	for range calls.Anything {
		m.EXPECT().Anything(mock.Anything).Return().Once()
	}
	return m
}
